spring:
  application:
    name: auction-service
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all          # wait for all replicas to acknowledge — no data loss
      retries: 3         # retry on failure
      properties:
        enable.idempotence: true   # prevent duplicate messages on retry
        spring.json.trusted.packages: "com.boli.*"
server:
  port: 8091
