spring:
  application:
    name: bidding-service
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all          # wait for all replicas to acknowledge — no data loss
      retries: 3         # retry on failure
      properties:
        enable.idempotence: true   # prevent duplicate messages on retry
        spring.json.trusted.packages: "com.boli.*"
    consumer:
      group-id: bidding-service-group
      auto-offset-reset: earliest # Read from beginning if no offset exists
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.boli.*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.boli.biddingservice.kafka.AuctionEvent
      data:
        redis:
          host: localhost
          port: 6379
server:
  port: 8092
