spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Let Gateway use Eureka to find services
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        # 1. Route for User Service
        - id: user-service
          uri: lb://USER-SERVICE # "lb://" means Load Balancer via Eureka
          predicates:
            - Path=/api/users/**

        # 2. Route for Auction Service
        - id: auction-service
          uri: lb://AUCTION-SERVICE
          predicates:
            - Path=/api/auctions/**

        # 3. Route for Bidding Service
        - id: bidding-service
          uri: lb://BIDDING-SERVICE
          predicates:
            - Path=/api/bids/**

        # 4. Route for Node.js Notification Service
        # Since Node isn't in Eureka, we hardcode the direct HTTP URL
        - id: notification-service
          uri: http://localhost:8093
          predicates:
            - Path=/api/notifications/**
  main:
    web-application-type: reactive
server:
  port: 8084
